Broadcast time for 1 processes: 0.000078 seconds
[thin005:2930407:0:2930407] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x7fb29aa3916e)
==== backtrace (tid:2930407) ====
 0  /lib64/libucs.so.0(ucs_handle_error+0x2e4) [0x7fb298093794]
 1  /lib64/libucs.so.0(+0x29e3d) [0x7fb298094e3d]
 2  /lib64/libucs.so.0(+0x2a025) [0x7fb298095025]
 3  /lib64/libc.so.6(+0x1691fc) [0x7fb29c58c1fc]
 4  /opt/programs/openMPI/4.1.5/lib/libopen-pal.so.40(opal_unsetenv+0x6b) [0x7fb29b60f20b]
 5  /opt/programs/openMPI/4.1.5/lib/libmpi.so.40(ompi_mpi_finalize+0x8ea) [0x7fb29b7a5b0a]
 6  /lib64/libpython3.11.so.1.0(+0x11ed95) [0x7fb29c71ed95]
 7  /lib64/libpython3.11.so.1.0(Py_RunMain+0x189) [0x7fb29c86f639]
 8  /lib64/libpython3.11.so.1.0(Py_BytesMain+0x3b) [0x7fb29c83652b]
 9  /lib64/libc.so.6(+0x27550) [0x7fb29c44a550]
10  /lib64/libc.so.6(__libc_start_main+0x89) [0x7fb29c44a609]
11  python(_start+0x25) [0x557ddf4df095]
=================================
/var/spool/slurm/d/job410231/slurm_script: line 16: 2930407 Segmentation fault      (core dumped) python performance_test.py
